### PR TITLE
update brickpi port prefix for ev3dev-2.0.0 kernel

### PR DESCRIPTION
**Pull request by dlech**
update the example as well

### CODE REVIEW

**Comment by kortschak** [comment]
Has this been tested? I tried this with an EV3 touch sensor and get the following:

```
$ ./sensor -driver lego-ev3-touch
2018/04/25 03:50:47 failed to find sensor: ev3dev: could not find device for driver "lego-ev3-touch" on port serial0-0:S1:i2c0
```

Has anything else changed about the organisation of the sysfs classes?

**Comment by dlech** [comment]
> on port serial0-0:S1:i2c0

the touch sensor is not an I2C sensor, so that is what is causing the problem

**Comment by dlech** [comment]
only i2c sensors should have the `:i2cX` suffix

**Comment by kortschak** [comment]
OK. That needs to be fixed then. I've just checked with the Lego Power Storage device and it works.

**Pull request merged**
